---
- name: configure my netoslab
  hosts: myhosts
  become: yes
  tasks:
    - name: change hostname
      ansible.builtin.hostname:
        name: netOSLab

    - name: set message in slim login screen
      ansible.builtin.lineinfile:
        path: /usr/share/slim/themes/debian-softwaves/slim.theme
        line: "{{ item.line }}"
        regexp: "{{ item.regexp }}"
      loop:
        - line: "password_x 200"
          regexp: ^password_x
        - line: "password_y 169"
          regexp: ^password_y
        - line: "username_msg Please entre your username (\"root\")"
          regexp: ^username_msg
        - line: "password_msg Please entre your password (\"netOSLab\")"
          regexp: ^password_msg

    - name: Create terminator config directory if it does not exist
      ansible.builtin.file:
        path: /root/.config/terminator
        state: directory
        mode: '0755'

    - name: set root terminator in green color
      ansible.builtin.copy:
        dest: /root/.config/terminator/config
        src: terminator-config
        force: no

    - name: change netOSLab boot logo
      ansible.builtin.copy:
        dest: /usr/share/systemback/splash.png
        src: splash.png

#    - name: enable server access control program for X from container
#      ansible.builtin.command:
#        cmd: xhost +local:docker

    - name: Clone all needed repos
      ansible.builtin.git:
        repo: "{{ item.repo }}"
        dest: "{{ item.dest }}"
      loop:   
        - repo: https://github.com/lpr-unsl/ssor.git
          dest: /root/Documents/ssor
        - repo: https://github.com/lpr-unsl/SimMemoria.git
          dest: /root/Documents/SimMemoria
        - repo: https://github.com/lpr-unsl/SimPlanificador.git
          dest: /root/Documents/SimPlanificador
    
    - name: Stop and Disable vsftpd service
      ansible.builtin.systemd_service:
        name: "{{ item.service }}"
        state: stopped
        enabled: false
      loop:
        - service: vsftpd
        - service: smbd
        - service: rpcbind
        - service: nfs-server
        - service: docker

    - name: Write netOslab tag in a version file
      ansible.builtin.shell: |
        git ls-remote --refs --tags https://github.com/lpr-unsl/netOSLab.git | tail -n1 > /root/Documents/netOSLab_version.txt
        git -C /root/Documents/ssor fetch https://github.com/lpr-unsl/netOSLab.git main
        git -C /root/Documents/ssor log --pretty=format:"%h %ad %s %d" --date=short FETCH_HEAD >> /root/Documents/netOSLab_version.txt

    - name: Unconditionally reboot the machine with new configuration
      ansible.builtin.reboot:
