---
- name: install packages
  hosts: myhosts
  become: yes
  tasks:
    - name: Update apt cache and a lot of packages
      apt:
        name: "{{ item }}"
        update_cache: yes
      loop:
        - ca-certificates
        - curl
          #- Xserver
        - slim
        - xfce4
        - terminator
          #- x11-xserver-utils
        - bridge-utils
        - libnet1
        - arping
        - wireshark
        - samba
        - smbclient
        - neovim
        - vsftpd
        - telnetd
        - firefox-esr

    - name: remove old version of docker
      apt:
        name: docker.io, docker-doc, docker-compose, podman-docker, containerd, runc
        state: absent

#    - name: create keyring directory
#      command: install -m 0755 -d /etc/apt/keyrings
#      #command: curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc

    # Docker-ce install documentation
    # https://docs.docker.com/engine/install/debian/#install-using-the-repository
    - name: create keyring directory
      shell: |
        install -m 0755 -d /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
         echo \
         "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian \
         $(. /etc/os-release && echo "$VERSION_CODENAME") stable" > /etc/apt/sources.list.d/docker.list

    - name: update cache, install docker
      apt:
        name: docker-ce, docker-ce-cli, containerd.io, docker-buildx-plugin, docker-compose-plugin
        update_cache: yes
        state: present

    - name: Enable and start docker service
      ansible.builtin.systemd_service:
        name: docker
        state: started
        enabled: true

